config/routes.rb
Rails.application.routes.draw do
  get 'songs/index'
  get 'songs/show'


  get 'albums/index'
  get 'albums/show'

  get 'artists/index'
  get 'artists/show'
root 'artists#index'

  resources :songs
  resources :artists
  resources :albums


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :songs
    belongs_to :artist  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :album
    # belongs_to :artist
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def create
    # @artist.create(params)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/index.html.erb
<h1>Albums</h1>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/artists/index.html.erb
<h1>Artist</h1>

<% @artists.each do |artist| %>

<ul>
<%= link_to artist.name, artists_index_path(artist), class: "btn btn-secondary btn-lg btn-block" %>
</ul>

<% end %>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SongsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header><nav><%= link_to 'Artist', artists_index_path %>
            <%= link_to 'Albums', albums_index_path %>
            <%= link_to 'Songs', songs_index_path %>
            </nav></header>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1>Songs</h1>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>